apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
  - port: 80          # Service port
    targetPort: 80    # Container port
    nodePort: 32080   # NodePort must be in 30000–32767
    protocol: TCP
